services:
  postgres:
    image: postgres
    container_name: key_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_keys
    volumes:
      - ./internal/store/keys/schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mongo:
    image: mongo
    container_name: url_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  url-cache:
    image: redis:7.4
    container_name: url_cache_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    command:  [
      "redis-server",
      "--maxmemory", "512mb",         
      "--maxmemory-policy", "allkeys-lru",
      "--loglevel", "warning"
    ]
    volumes:
      - url_cache_data:/data

  key-cache:
    image: redis:7.4
    container_name: key_cache_container
    restart: unless-stopped
    ports:
      - "6380:6379"
    command:  [
      "redis-server",
      "--loglevel", "warning"
    ]
    volumes:
      - key_cache_data:/data

volumes:
  postgres_data:
  mongo_data:
  url_cache_data:
  key_cache_data:
 